spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
        #           filters:
        #             - AuthFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**

    consul:
      discovery:
        instanceId: ${spring.application.name}
        health-check-interval: 15s
      config:
        management:
          enabled: true
      host: localhost

  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: 576D5A7134743777217A25432646294A404E635266556A586E3272357538782F